name: laravel_build_images

on:
  push:
    branches:
      - master
    paths:
      - 'laravel/**'
      - 'ubuntu/**'
      - 'php-fpm/**'
      - 'alpine/**'
  pull_request:
    branches:
      - master
    paths:
      - 'laravel/**'
      - 'ubuntu/**'
      - 'php-fpm/**'
      - 'alpine/**'

jobs:
  build:
    name: publish image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: |
        echo ${{ secrets.PAT }} | docker login ${{ env.REGISTRY }} -u ${{ env.REGISTRY_USER }} --password-stdin        
    - name: tag 8.1-fpm-alpine build
      run: docker-compose --env-file build-env-files/alpine/81/.env-mysql -f build-alpine.yml build --pull
